### ISSUE TITLE
LZ_security - keeper/AddReputerNonce or AddWorkerNonce When the Nonce reaches the maximum value, an error occurs

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-allora-judging#103]
LZ_security

Medium

# keeper/AddReputerNonce or AddWorkerNonce When the Nonce reaches the maximum value, an error occurs

## Summary
keeper/AddReputerNonce or AddWorkerNonce When the number of Nonce reaches the maximum, 
the error of removing the old nonce causes the Nonce cannot be added

## Vulnerability Detail

The `AddReputerNonce` function, as in the comment, if nonces reaches its maximum, removes the old nonce,

But instead of actually removing the old element, it mistakenly removed the new element,

nonces.Nonces = nonces.Nonces[:maxUnfulfilledRequests]

```go
// Adds a nonce to the unfulfilled nonces for the topic if it is not yet added (idempotent).
// If the max number of nonces is reached, then the function removes the oldest nonce and adds the new nonce.
func (k *Keeper) AddReputerNonce(ctx context.Context, topicId TopicId, nonce *types.Nonce, associatedWorkerNonce *types.Nonce) error {
	nonces, err := k.GetUnfulfilledReputerNonces(ctx, topicId)
	......
	maxUnfulfilledRequests := moduleParams.MaxUnfulfilledReputerRequests
	lenNonces := uint64(len(nonces.Nonces))
	if lenNonces > maxUnfulfilledRequests {
		diff := uint64(len(nonces.Nonces)) - maxUnfulfilledRequests
		if diff > 0 {
@>			nonces.Nonces = nonces.Nonces[:maxUnfulfilledRequests]
		}
	}
	return k.unfulfilledReputerNonces.Set(ctx, topicId, nonces)
}
```

It's the same problem with `AddWorkerNonce`.

## Impact
The Nonce cannot be added, resulting in the failure to add worker data and loose data,and the protocol cannot work.

## Code Snippet
https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/keeper.go#L378-L423

## Tool used

Manual Review

## Recommendation
```diff
-    nonces.Nonces = nonces.Nonces[:maxUnfulfilledRequests]
+    nonces.Nonces = nonces.Nonces[diff:maxUnfulfilledRequests]
```

**Comment by 0502lian** [comment]
Escalate

This issue is valid. It is a very obvious mathematical error (an error in array slicing).

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue is valid. It is a very obvious mathematical error (an error in array slicing).

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by ZeroTrust01** [comment]
Escalate

This issue is valid. It is a very obvious mathematical error (an error in array slicing).

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue is valid. It is a very obvious mathematical error (an error in array slicing).

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by imsrybr0** [comment]
Hi @ZeroTrust01, the added Nonce is prepended not appended (https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/keeper.go#L408).

**Comment by mystery0x** [comment]
> Escalate
> 
> This issue is valid. It is a very obvious mathematical error (an error in array slicing).

The nonce is prepended rather than appended, meaning `nonces.Nonces[:maxUnfulfilledRequests]` is intended behavior

**Comment by ZeroTrust01** [comment]
> > Escalate
> > This issue is valid. It is a very obvious mathematical error (an error in array slicing).
> 
> The nonce is prepended rather than appended, meaning `nonces.Nonces[:maxUnfulfilledRequests]` is intended behavior


Indeed, I made a mistake here.

**Comment by WangSecurity** [comment]
Since the escalation and the report is false, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ZeroTrust01](https://github.com/sherlock-audit/2024-06-allora-judging/issues/103/#issuecomment-2282358007): rejected
