### ISSUE TITLE
volodya - incorrect default genesis state in emission module

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-allora-judging#20]
volodya

Medium

# incorrect default genesis state in emission module

## Summary
incorrect default genesis state in emission module 
## Vulnerability Detail
Input params are missing inside state generation for `types.NewGenesisState()`
```go
func (AppModule) DefaultGenesis(cdc codec.JSONCodec) json.RawMessage {
	return cdc.MustMarshalJSON(types.NewGenesisState())
}
```
[emissions/module/module.go#L79](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/module/module.go#L79)
If we will look at `NewGenesisState` it accepts params, so incorrect state will be generated
```go
func NewGenesisState(
	params Params,
	previousRewardEmissionPerUnitStakedToken math.LegacyDec,
	previousBlockEmission math.Int,
	ecosystemTokensMinted math.Int,
) *GenesisState {
	return &GenesisState{
		Params:                                   params,
		PreviousRewardEmissionPerUnitStakedToken: previousRewardEmissionPerUnitStakedToken,
		PreviousBlockEmission:                    previousBlockEmission,
		EcosystemTokensMinted:                    ecosystemTokensMinted,
	}
}
```
## Impact
Incorrect state params generation
## Tool used

Manual Review

## Recommendation
Pass appropriate params or use `cdc.MustMarshalJSON(types.DefaultGenesisState())`

**Comment by ZeroTrust01** [comment]
Escalate

This issue is invalid.
we can see that
https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/emissions/module/module.go#L79

types.NewGenesisState() calls the function NewGenesisState(), not the function NewGenesisState(
	params Params,
	previousRewardEmissionPerUnitStakedToken math.LegacyDec,
	previousBlockEmission math.Int,
	ecosystemTokensMinted math.Int,
)

```go
func NewGenesisState() *GenesisState {
	return &GenesisState{
		Params:            DefaultParams(),
@>>		CoreTeamAddresses: DefaultCoreTeamAddresses(),
	}
}
```
https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/emissions/types/genesis.go#L8

https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/mint/types/genesis.go#L6

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue is invalid.
> we can see that
> https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/emissions/module/module.go#L79
> 
> types.NewGenesisState() calls the function NewGenesisState(), not the function NewGenesisState(
> 	params Params,
> 	previousRewardEmissionPerUnitStakedToken math.LegacyDec,
> 	previousBlockEmission math.Int,
> 	ecosystemTokensMinted math.Int,
> )
> 
> ```go
> func NewGenesisState() *GenesisState {
> 	return &GenesisState{
> 		Params:            DefaultParams(),
> @>>		CoreTeamAddresses: DefaultCoreTeamAddresses(),
> 	}
> }
> ```
> https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/emissions/types/genesis.go#L8
> 
> https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/mint/types/genesis.go#L6
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
> Escalate
> 
> This issue is invalid. we can see that https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/emissions/module/module.go#L79
> 
> types.NewGenesisState() calls the function NewGenesisState(), not the function NewGenesisState( params Params, previousRewardEmissionPerUnitStakedToken math.LegacyDec, previousBlockEmission math.Int, ecosystemTokensMinted math.Int, )
> 
> ```go
> func NewGenesisState() *GenesisState {
> 	return &GenesisState{
> 		Params:            DefaultParams(),
> @>>		CoreTeamAddresses: DefaultCoreTeamAddresses(),
> 	}
> }
> ```
> 
> https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/emissions/types/genesis.go#L8
> 
> https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/mint/types/genesis.go#L6

Agree that this issue is invalid, DefaultGenesis uses NewGenesisState() function that does not require any parameters already.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept it and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ZeroTrust01](https://github.com/sherlock-audit/2024-06-allora-judging/issues/20/#issuecomment-2282367722): accepted
