### ISSUE TITLE
volodya - errors are not being handled which can lead to executing code with errors(silencing them) or a halt chain due to panic

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-allora-judging#24]
volodya

Medium

# errors are not being handled which can lead to executing code with errors(silencing them) or a halt chain due to panic

## Summary
returns from ".Set" ".Get" are not being handled which can lead to executing code with errors or a halt chain.
## Vulnerability Detail
error from SetDelegateStakePlacement is not handling like it is done in another part of the codebase
```go
		if err != nil {
			return nil, err
		}
		ms.k.SetDelegateStakePlacement(ctx, msg.TopicId, msg.Sender, msg.Reputer, delegateInfo)
	}
```
[msg_server_stake.go#L303](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/msgserver/msg_server_stake.go#L303)

```go
	if err := k.SetDelegateStakePlacement(ctx, topicId, delegator, reputer, stakePlacementNew); err != nil {
		return errorsmod.Wrapf(err, "Setting delegate stake placement failed")
	}
```
[emissions/keeper/keeper.go#L1052](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/keeper.go#L1052)

Other examples
```go
					am.keeper.PruneReputerNonces(sdkCtx, topic.Id, reputerPruningBlock)

```
[emissions/module/abci.go#L92](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/module/abci.go#L92)

```go
func (am AppModule) InitGenesis(ctx sdk.Context, cdc codec.JSONCodec, data json.RawMessage) {
	var genesisState types.GenesisState
	cdc.MustUnmarshalJSON(data, &genesisState)

	am.keeper.InitGenesis(ctx, am.authKeeper, &genesisState)
}
```
[x/mint/module/module.go#L126](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/mint/module/module.go#L126)

```go
						am.keeper.PruneWorkerNonces(sdkCtx, topic.Id, workerPruningBlock)

```
[emissions/module/abci.go#L99](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/module/abci.go#L99)

```go
		k.AddWhitelistAdmin(ctx, addr)
```
[genesis.go#L59](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/genesis.go#L59)

```go
		k.SetInfererNetworkRegret(ctx, topicId, infererLoss.Worker, newInfererRegret)
```
[/inference_synthesis/network_regrets.go#L121](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/inference_synthesis/network_regrets.go#L121)

```diff
func (k *Keeper) ResetChurnableTopics(ctx context.Context) error {
-	k.churnableTopics.Clear(ctx, nil)
-	return nil
+    return k.churnableTopics.Clear(ctx, nil)
}
```
[emissions/keeper/keeper.go#L1749](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/keeper.go#L1749)

multiple others in code
## Tool used

Manual Review

## Recommendation
Implement correct error handling

**Comment by 0xVolodya** [comment]
Escalate
I believe this is HIGH, theft-of-funds, According to team PR 
> In the case of RewardDelegateStake, we silently ignore errors allowing transactions to continue with errors, which allows Delegators to claim rewards multiple times. This is actually a serious theft-of-funds bug.

[audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/msgserver/msg_server_stake.go#L303)](https://github.com/allora-network/allora-chain/pull/463)

**Comment by sherlock-admin3** [comment]
> Escalate
> I believe this is HIGH, theft-of-funds, According to team PR 
> > In the case of RewardDelegateStake, we silently ignore errors allowing transactions to continue with errors, which allows Delegators to claim rewards multiple times. This is actually a serious theft-of-funds bug.
> 
> [audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/msgserver/msg_server_stake.go#L303)](https://github.com/allora-network/allora-chain/pull/463)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xVolodya** [comment]
I think this issue and these the same
https://github.com/sherlock-audit/2024-06-allora-judging/issues/30

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/allora-network/allora-chain/pull/507

**Comment by mystery0x** [comment]
> Escalate I believe this is HIGH, theft-of-funds, According to team PR
> 
> > In the case of RewardDelegateStake, we silently ignore errors allowing transactions to continue with errors, which allows Delegators to claim rewards multiple times. This is actually a serious theft-of-funds bug.
> 
> [audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/msgserver/msg_server_stake.go#L303)](https://github.com/allora-network/allora-chain/pull/463)


The report highlights that errors aren't being handled, which could lead to unintended behavior, but it didn't explicitly talk about the impact (e.g., multiple reward claims or direct financial losses). The impact is also empty. I would say report is too vague for high severity

**Comment by WangSecurity** [comment]
I agree with the last comment from the Lead Judge. Indeed the report doesn't have sufficient proof that this issue can indeed happen and that it leads to any impact.

Planning to reject the escalation since it asks to increase the severity and invalidate the report.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xVolodya](https://github.com/sherlock-audit/2024-06-allora-judging/issues/24/#issuecomment-2277207333): rejected
