### ISSUE TITLE
0xsi - Potential for Uncontrolled Resource Consumption in `topics_handler.go`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-allora-judging#32]
0xsi

High

# Potential for Uncontrolled Resource Consumption in `topics_handler.go`

## Summary
There is no ressource consumption check in `requestTopicWorkers` and `requestTopicReputers` which can lead to dangerous scenarios.

## Vulnerability Detail
The use of goroutines in `requestTopicWorkers` and `requestTopicReputers` without proper limits can lead to uncontrolled resource consumption. If the number of topics or nonces is large, it can spawn a large number of goroutines, leading to potential resource exhaustion.

## Impact
Uncontrolled spawning of goroutines can lead to excessive resource consumption, causing performance degradation, potential crashes, or denial of service.

## Code Snippet
https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/app/topics_handler.go#L74-L78

https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/app/topics_handler.go#L101-L127

## Tool used

Manual Review

## Recommendation
Implement a mechanism to limit the number of concurrent goroutines. Use worker pools or similar constructs to control resource usage and prevent exhaustion.

**Comment by ZeroTrust01** [comment]
Escalate
This issue should not be high.

In Go, goroutines and threads are not the same concept. Goroutines in Go only consume memory. The number of goroutines in Go is virtually unlimited.
> On a machine with 4 GB of memory installed, this limits the maximum number of goroutines to slightly less than 1 million.

https://stackoverflow.com/questions/8509152/max-number-of-goroutines


Furthermore, the number of Reputers and Workers in this protocol is limited, so it is not possible to cause potential crashes or denial of service.

**Comment by sherlock-admin3** [comment]
> Escalate
> This issue should not be high.
> 
> In Go, goroutines and threads are not the same concept. Goroutines in Go only consume memory. The number of goroutines in Go is virtually unlimited.
> > On a machine with 4 GB of memory installed, this limits the maximum number of goroutines to slightly less than 1 million.
> 
> https://stackoverflow.com/questions/8509152/max-number-of-goroutines
> 
> 
> Furthermore, the number of Reputers and Workers in this protocol is limited, so it is not possible to cause potential crashes or denial of service.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
> Escalate This issue should not be high.
> 
> In Go, goroutines and threads are not the same concept. Goroutines in Go only consume memory. The number of goroutines in Go is virtually unlimited.
> 
> > On a machine with 4 GB of memory installed, this limits the maximum number of goroutines to slightly less than 1 million.
> 
> https://stackoverflow.com/questions/8509152/max-number-of-goroutines
> 
> Furthermore, the number of Reputers and Workers in this protocol is limited, so it is not possible to cause potential crashes or denial of service.

I agree. The risk of excessive resource consumption will likely not happen

**Comment by WangSecurity** [comment]
As I understand, with the constraints represented in the escalation comment, this issue doesn't warrant even medium severity.

Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ZeroTrust01](https://github.com/sherlock-audit/2024-06-allora-judging/issues/32/#issuecomment-2282969448): accepted
