### ISSUE TITLE
volodya - The chain will not be in the correct state when upgraded via a hard fork.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-allora-judging#42]
volodya

High

# The chain will not be in the correct state when upgraded via a hard fork.

## Summary
The chain will not be in the correct state when upgraded via a hard fork.
## Vulnerability Detail
According to [cosmos SDK](https://docs.cosmos.network/main/build/building-modules/genesis#exportgenesis)
>The ExportGenesis method is executed whenever an export of the state is made. It takes the latest known version of the subset of the state managed by the module and creates a new GenesisState out of it. This is mainly used when the chain needs to be upgraded via a hard fork.

There should be whole state imported inside `ExportGenesis` not only moduleParams, everything from `InitGenesis` and any other state that is being mutated inside emissions module, just like its done for [mint module](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/mint/keeper/genesis.go#L36) otherwise fork would unsucessfull
```go
func (k *Keeper) InitGenesis(ctx context.Context, data *types.GenesisState) error {
	// ensure the module account exists
	stakingModuleAccount := k.authKeeper.GetModuleAccount(ctx, types.AlloraStakingAccountName)
	k.authKeeper.SetModuleAccount(ctx, stakingModuleAccount)
	alloraRewardsModuleAccount := k.authKeeper.GetModuleAccount(ctx, types.AlloraRewardsAccountName)
	k.authKeeper.SetModuleAccount(ctx, alloraRewardsModuleAccount)
	alloraPendingRewardsModuleAccount := k.authKeeper.GetModuleAccount(ctx, types.AlloraPendingRewardForDelegatorAccountName)
	k.authKeeper.SetModuleAccount(ctx, alloraPendingRewardsModuleAccount)
	if err := k.SetParams(ctx, data.Params); err != nil {
		return err
	}
	if err := k.SetTotalStake(ctx, cosmosMath.ZeroInt()); err != nil {
		return err
	}
	// reserve topic ID 0 for future use
	if _, err := k.IncrementTopicId(ctx); err != nil {
		return err
	}

	// add core team to the whitelists
	if err := k.addCoreTeamToWhitelists(ctx, data.CoreTeamAddresses); err != nil {
		return err
	}

	// For mint module inflation rate calculation set the initial
	// "previous percentage of rewards that went to staked reputers" to 30%
	if err := k.SetPreviousPercentageRewardToStakedReputers(ctx, alloraMath.MustNewDecFromString("0.3")); err != nil {
		return err
	}

	return nil
}
// ExportGenesis exports the module state to a genesis state.
func (k *Keeper) ExportGenesis(ctx context.Context) (*types.GenesisState, error) {
	moduleParams, err := k.GetParams(ctx)
	if err != nil {
		return nil, err
	}

	return &types.GenesisState{
		Params: moduleParams,
	}, nil
}
```
[emissions/keeper/genesis.go#L46](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/genesis.go#L46)
## Tool used

Manual Review

## Recommendation
Export whole state inside `ExportGenesis`
```diff
func (k *Keeper) ExportGenesis(ctx context.Context) (*types.GenesisState, error) {
	moduleParams, err := k.GetParams(ctx)
+	totalStake, err := k.GetTotalStake(ctx)
+	previousPercentageRewardToStakedReputers, err := k.GetPreviousPercentageRewardToStakedReputers(ctx)
	...
	if err != nil {
		return nil, err
	}

	return &types.GenesisState{
+		Params:     moduleParams,
+		totalStake: totalStake,
+		previousPercentageRewardToStakedReputers: previousPercentageRewardToStakedReputers,
		...
	}, nil
}
```

**Comment by ZeroTrust01** [comment]
Escalate
This issue should not be high.
The impact of the issue is high, but  the likelihood of a hard fork occurring is extremely low.

**Comment by sherlock-admin3** [comment]
> Escalate
> This issue should not be high.
> The impact of the issue is high, but  the likelihood of a hard fork occurring is extremely low.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xVolodya** [comment]
I think its high, e.x. osmosis had a hard fork once a year. There was[25 versions](https://github.com/osmosis-labs/osmosis/releases?q=fork&expanded=true)  some of them require hard fork. There are multiple HIGH issues with ddos which are really unlikely to happen in cosmos projects, while the hard fork will result in an incorrect state 100%.

**Comment by zhaojio** [comment]
> I think its high, e.x. osmosis had a hard fork once a year. There was[25 versions](https://github.com/osmosis-labs/osmosis/releases?q=fork&expanded=true) some of them require hard fork. There are multiple HIGH issues with ddos which are really unlikely to happen in cosmos projects, while the hard fork will result in an incorrect state 100%.

> osmosis had a hard fork once a year. 

But not all projects need to use hard forks.

**Comment by WangSecurity** [comment]
I agree that the example of the other chains is not relevant, cause I'm sure we can find an example of the chain that had no hard forks at all.

But, I don't see the impact in the report. Yeah, I see it doesn't take the entire state, but I don't see any explanation of how it would impact the chain, am I missing something here?

**Comment by 0xVolodya** [comment]
Incorrect export of the state in case of emergency( upgraded via a hard fork) would lead to loss of chain data, according to protocol change, as you can see from its commit. I did mention it in my issue that state would be incorrect

```go
func (k *Keeper) ExportGenesis(ctx context.Context) (*types.GenesisState, error) {
...
	return &types.GenesisState{
		Params:                                         moduleParams,
		NextTopicId:                                    nextTopicId,
		Topics:                                         topics,
		ActiveTopics:                                   activeTopics,
		RewardableTopics:                               rewardableTopics,
		TopicWorkers:                                   topicWorkers,
		TopicReputers:                                  topicReputers,
		TopicRewardNonce:                               topicRewardNonce,
		InfererScoresByBlock:                           infererScoresByBlock,
		ForecasterScoresByBlock:                        forecasterScoresByBlock,
		ReputerScoresByBlock:                           reputerScoresByBlock,
...
```
[emissions/keeper/genesis.go#L1586](https://github.com/allora-network/allora-chain/blob/baf549728f33a68e155dead35076a22359d22a31/x/emissions/keeper/genesis.go#L1586)

**Comment by WangSecurity** [comment]
Thank you for the clarifications. Indeed the report identifies the root cause, but I believe it doesn't explain any medium impact. The issue only states that the hard fork will be unsuccessful, which is too vague and not sufficient. Hence, I believe the report has to be invalid, planning to accept the escalation and invalidate the report.

**Comment by 0xVolodya** [comment]
Isn't this one the same as this https://github.com/sherlock-audit/2024-06-allora-judging/issues/89? It's medium

**Comment by WangSecurity** [comment]
#89 has a clearly defined medium-severity impact, while this report doesn't. That's why I believe it should be invalid, planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ZeroTrust01](https://github.com/sherlock-audit/2024-06-allora-judging/issues/42/#issuecomment-2282971941): accepted
