### ISSUE TITLE
Kow - Topic could be activated despite not meeting the minimum topic weight threshold due to double counting of added fee revenue

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-allora-judging#75]
Kow

Medium

# Topic could be activated despite not meeting the minimum topic weight threshold due to double counting of added fee revenue

## Summary
Topic could be activated despite not meeting the minimum topic weight threshold due to double counting of added fee revenue.

## Vulnerability Detail
In `FundTopic`, after updating the topic fee revenue, the topic may be activated if its new topic weight meets the minimum threshold in `activateTopicIfWeightAtLeastGlobalMin`. 
https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/emissions/keeper/msgserver/msg_server_util_topic_activation.go#L13-L47
```go
func activateTopicIfWeightAtLeastGlobalMin(ctx context.Context, ms msgServer, topicId TopicId, amount Allo) error {
	...
	if !isActivated {
		params, err := ms.k.GetParams(ctx)
		...
		topic, err := ms.k.GetTopic(ctx, topicId)
		...
		newTopicWeight, _, err := ms.k.GetCurrentTopicWeight(
			ctx,
			topicId,
			topic.EpochLength,
			params.TopicRewardAlpha,
			params.TopicRewardStakeImportance,
			params.TopicRewardFeeRevenueImportance,
			amount,
		)
		...
		if newTopicWeight.Gte(params.MinTopicWeight) {
			err = ms.k.ActivateTopic(ctx, topicId)
			...
	}
```
In `GetCurrentTopicWeight`, the total fee revenue of the topic is first calculated as `topicFeeRevenue + additionalRevenue`. 
https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/emissions/keeper/topic_weight.go#L55-L68
```go
	topicStakeDec, err := alloraMath.NewDecFromSdkInt(topicStake)
	...
	// Get and total topic fee revenue
	topicFeeRevenue, err := k.GetTopicFeeRevenue(ctx, topicId)
	...
	// Calc target weight using fees, epoch length, stake, and params
	newFeeRevenue := additionalRevenue.Add(topicFeeRevenue)
	feeRevenue, err := alloraMath.NewDecFromSdkInt(newFeeRevenue)
```
The issue is even though the fee revenue was added to the total fee revenue before this call (in `AddTopicFeeRevenue`), such that `topicFeeRevenue` already includes the newly added fee revenue, `amount` is still passed in as the `additionalRevenue` parameter. Consequently, the added fee revenue is always double counted when checking topic weight for activation in `FundTopic` (only in the checked value, not committed to state).

## Impact
The calculated topic weight is inflated and could result in the topic being activated despite not meeting the threshold. In the emissions module `EndBlocker`, active topics are dripped (their fee revenue decays) if their epoch is ending. Consequently, a topic that should be inactive could lose fee revenue even though they are not actively considered in the churning process.

## Code Snippet
https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/emissions/keeper/msgserver/msg_server_util_topic_activation.go#L13-L47
https://github.com/sherlock-audit/2024-06-allora/blob/4e1bc73db32873476f8b0a88945815d3978d931c/allora-chain/x/emissions/keeper/topic_weight.go#L55-L68

## Tool used

Manual Review

## Recommendation
Call `GetCurrentTopicWeight` with `additionalRevenue = 0`.

Duplicate of #46

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/allora-network/allora-chain/pull/505
