### ISSUE TITLE
0x3b - `required_minimum_stake` is not verified when registering network participants

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-allora-judging#86]
0x3b

High

# `required_minimum_stake` is not verified when registering network participants

### Summary
In order to register, workers or reputers should have at least 100 allo staked. However, `Register` doesn't check for this.

### Vulnerability Detail
The Allora docs state that to register network participants, whether reputers or workers, they need to have a minimum stake of 100 allo.

https://docs.allora.network/devs/reference/params/chain#required_minimum_stake
> Sets the minimum stake to be a worker or reputer. If a worker or reputer has less than this stake, then it is not eligible for rewards. This is set at worker and reputer registration.

> Default Value: 100 allo

However, this is not the case, as [Register](https://github.com/sherlock-audit/2024-06-allora/blob/main/allora-chain/x/emissions/keeper/msgserver/msg_server_registrations.go#L14) will register and insert them into the worker/reputer array without checking any stake balances. The only allo check it does is if they have enough of it to pay the registration fee.

```go
func (ms msgServer) CheckBalanceForRegistration(ctx context.Context, address string) (bool, sdk.Coin, error) {
	moduleParams, err := ms.k.GetParams(ctx)
	if err != nil {
		return false, sdk.Coin{}, err
	}
	fee := sdk.NewCoin(params.DefaultBondDenom, moduleParams.RegistrationFee)
```

Missing a min stake requirement can be potentially dangerous for the system, as it enables participants to participate without offering any backing/commitment.

### Impact
Workers and reputers don't need a minimum stake to participate in the system. This can also pose a threat to the security of the whole system.

### Code Snippet
```go
func (ms msgServer) Register(ctx context.Context, msg *types.MsgRegister) (*types.MsgRegisterResponse, error) {
    if err := msg.Validate(); err != nil {
        return nil, err
    }

    topicExists, err := ms.k.TopicExists(ctx, msg.TopicId)
    if err != nil {
        return nil, err
    }
    if !topicExists {
        return nil, types.ErrTopicDoesNotExist
    }

    //@audit doesn't check for min balance of stakers
    hasEnoughBal, fee, err := ms.CheckBalanceForRegistration(ctx, msg.Sender)
    if err != nil {
        return nil, err
    }
    if !hasEnoughBal {
        return nil, types.ErrTopicRegistrantNotEnoughDenom
    }

    // Before creating topic, transfer fee amount from creator to ecosystem bucket
    err = ms.k.SendCoinsFromAccountToModule(ctx, msg.Sender, mintTypes.EcosystemModuleName, sdk.NewCoins(fee))
    if err != nil {
        return nil, err
    }

    nodeInfo := types.OffchainNode{
        NodeAddress:  msg.Sender,
        LibP2PKey:    msg.LibP2PKey,
        MultiAddress: msg.MultiAddress,
        Owner:        msg.Owner,
        NodeId:       msg.Owner + "|" + msg.LibP2PKey,
    }

    if msg.IsReputer {
        err = ms.k.InsertReputer(ctx, msg.TopicId, msg.Sender, nodeInfo)
        if err != nil {
            return nil, err
        }
    } else {
        err = ms.k.InsertWorker(ctx, msg.TopicId, msg.Sender, nodeInfo)
        if err != nil {
            return nil, err
        }
    }

    return &types.MsgRegisterResponse{
        Success: true,
        Message: "Node successfully registered",
    }, nil
}
```

### Tool Used
Manual Review

### Recommendation
Include a check to verify that the registered party has staked at least `RequiredMinimumStake`.

**Comment by imsrybr0** [comment]
Escalate

The documentation being wrong is not enough for this to be a valid issue.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> The documentation being wrong is not enough for this to be a valid issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0x3b33** [comment]
> The documentation being incorrect is not sufficient to make this a valid issue.

Given the issue at hand, it can be assumed that the documentation describes the code. The report clearly indicates that this is not the case, showing the actual code and the parts of the documentation that contradict each other.

In this instance, the fault was with the documentation, not the code. However, with the before-fix knowledge of the codebase and documentation, would this have been considered an issue? Yes, it would have been. 

Additionally, the developer clearly made a fix.

**Comment by mystery0x** [comment]
> Escalate
> 
> The documentation being wrong is not enough for this to be a valid issue.

The report highlighted a discrepancy between the documentation and the code, which would've made the issue valid before the documentation was updated. 

Although it has since been clarified that the code was correct and the documentation was not, this wouldn't have been clear beforehand. I would consider this valid still.

**Comment by zhaojio** [comment]
> > Escalate
> > The documentation being wrong is not enough for this to be a valid issue.
> 
> The report highlighted a discrepancy between the documentation and the code, which would've made the issue valid before the documentation was updated.
> 
> Although it has since been clarified that the code was correct and the documentation was not, this wouldn't have been clear beforehand. I would consider this valid still.

This should not be high, the severity should be based on the impact it has, and the issue simply points out that the code is inconsistent with the documentation.

> If a reputer does not have enough stake,  they won't be able to upload loss bundles. If they aren't able to upload loss bundles, they get no rewards,  later when rewards are calculated.

This problem is not identified in the report, and this is the user's (staker) fault, since it has been documented that a stake greater than 100 allo is required.

**Comment by 0x3b33** [comment]
> This should not be high, the severity should be based on the impact it has, and the issue simply points out that the code is inconsistent with the documentation.

To judge the severity in this case would be complicated, given the feedback from the sponsor. However I stand with my original explanation:

> In this instance, the fault was with the documentation, not the code. However, with the before-fix knowledge of the codebase and documentation, would this have been considered an issue? Yes, it would have been.

> Additionally, the developer clearly made a fix.

If it would have been the case that the code was wrong and the docs right, which severity would have been most appropriate for this issue ? I think high would still make sense.

**Comment by imsrybr0** [comment]
Hi @0x3b33,

> If it would have been the case that the code was wrong and the docs right, which severity would have been most appropriate for this issue ? I think high would still make sense.

Yes, it would have been a Medium/High based on the size of the loss but it doesn't make this issue any more valid.

The argument "If I was right, then the issue would have been valid" is applicable to any invalid issue.

In this case, the assumption was that the code was missing a check but it turned out that the docs were misleading and the code wasn't missing anything.

In addition to that, the issue was clearly in the documentation since if it wasn't, it would have created a different problem : Registering a reputer would require a minimum stake but staking requires a registered reputer.

In summary, there are no losses for users or the chain and no major functionality is broken / missing.

**Comment by 0x3b33** [comment]
> The argument "If I was right, then the issue would have been valid" is applicable to any invalid issue.

That statement is misleading. The [comment](https://github.com/sherlock-audit/2024-06-allora-judging/issues/86#issuecomment-2287979138) doesn't state "If I was right, then the issue would have been valid". 

My comment implies that during the contest we didn't have the knowledge on which is wrong, docs or code, so the issue was submitted with the effect of code being wrong.

Although I can agree with you that med can more appropriate for this specific issue.

**Comment by WangSecurity** [comment]
Firstly, the sponsor fixing an issue doesn't affect the decision. Additionally, the PR is to change the documentation, not the code.

Secondly, keep in mind that the protocol docs don't stand above the rules. It's still a good source to understand the protocol's intentions, but it doesn't mean the issues breaking statements in the docs are necessarily valid.

Finally, I see the report says `Missing a min stake requirement can be potentially dangerous for the system, as it enables participants to participate without offering any backing/commitment`. But, as I understand the code is intended so it doesn't lead to any loss of broken functionality? Additionally, the statement in the `Impact` section is vague and doesn't have a medium impact.

Before making the decision, waiting for an answer to the question above.

**Comment by 0x3b33** [comment]
You are right, we can leave that as invalid, it would be a thought to defend a change in docs as med, when the reputers will get no reward for participating.

**Comment by WangSecurity** [comment]
Planning to accept the escalation and invalidate the report.

**Comment by 0x3b33** [comment]
Agree with the decision

**Comment by WangSecurity** [comment]
Result:
Invalid 
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [imsrybr0](https://github.com/sherlock-audit/2024-06-allora-judging/issues/86/#issuecomment-2282235460): accepted
